server:
  port: 8080

spring:
  profiles:
    active: dev
  #Redis
  redis:
    host: 127.0.0.1
  #Mysql
  datasource:
    #数据源基本配置
    username: root
    password: 123456789
    url: jdbc:mysql:///feishuchatgpt?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 6000
mybatis:
  type-aliases-package: com.zerodstocking.feishuchatgpt.dal.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

feishu:
  appId:
  appSecret:
  baseURL: https://open.feishu.cn
  encryptKey:
  verificationToken:

openai:
  baseURL: https://api.openai.com
  apiKey:
  organizationId:
